### ISSUE TITLE
Owner Problems On Termial!

### ISSUE THREAD

**Issue by haaddaa1** [Nerdietony/Nerdie-Cogs#6]
Ignoring exception in message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/Users/    /Desktop/G/Red-DiscordBot/cogs/selfembed.py", line 33, in on_message
    if self.eee["toggle"] and author.id == self.bot.owner.user.id:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Bot'>' object has no attribute 'owner'

**HELP**

**Comment by haaddaa1** [comment]
hello?

**Comment by Nerdietony** [comment]
Sorry, you need to update selfembed to the latest version and run the setowner command.

**Comment by haaddaa1** [comment]
ok

**Comment by haaddaa1** [comment]
wait how do i update lol

**Comment by Nerdietony** [comment]
If you added the cog via command then use [p]cog update ([p] being your prefix) .

**Comment by haaddaa1** [comment]
i did that

**Comment by Nerdietony** [comment]
Ok, then it should be updated.

**Comment by haaddaa1** [comment]
do i turn off my bot then turn it back on

**Comment by haaddaa1** [comment]
and i also have tons of cogs like 117 cogs

**Comment by Nerdietony** [comment]
It shoud've automatically reloaded it. Try `[p]reload selfembed` while [p] being your bot's prefix

**Comment by haaddaa1** [comment]
im still getting 
 Ignoring exception in message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/Users/ /Desktop/G/Red-DiscordBot/cogs/selfembed.py", line 44, in on_message
    if self.eee["toggle"] and author.id == self.eee["id"]:
KeyError: 'id'
≈Ignoring exception in message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/Users/ /Desktop/G/Red-DiscordBot/cogs/selfembed.py", line 44, in on_message
    if self.eee["toggle"] and author.id == self.eee["id"]:
KeyError: 'id'

**Comment by haaddaa1** [comment]
should i just take i off

**Comment by Nerdietony** [comment]
Nope, now just run the command `[p]setowner` and it should work fine

**Comment by haaddaa1** [comment]
ok

**Comment by haaddaa1** [comment]
now this 
 Ignoring exception in voice_state_update
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/Users/user/Desktop/G/Red-DiscordBot/cogs/dynamicvoice.py", line 191, in check_voice
    cache = self.settings[server.id]['cache']
KeyError: '285260739571089408'

**Comment by Nerdietony** [comment]
That is from another repo that is not made by me. Please contact the people who made the DynamicVoice, thx. Closing issue unless u need anymore help.

**Comment by haaddaa1** [comment]
ok
